survey/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

survey/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('resultsdata/<str:obj>/', views.resultData, name="resultsdata")
]

survey/survey/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

survey/pages/models.py
from django.db import models

# Create your models here.

survey/poll/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

survey/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

survey/poll/views.py
from django.shortcuts import render, Http404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.http import JsonResponse
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)
    # return HttpResponse('<h1>Hello</h1>')

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question doesn't exist")
    return render(request, 'poll/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print("Request POST data:", request.POST)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))
    
def resultData(request, obj):
    voteData = []
    question = Question.objects.get(id=obj)
    votes = question.choice_set.all()

    for i in votes:
        voteData.append({i.choice_text : i.votes})

    print(voteData)
    return JsonResponse(voteData, safe=False)

survey/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Survey Hub {% block title %}{% endblock %}</title>
    <!-- <style>
        .badge{
            background-color: 
        }
    </style> -->
</head>
<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

survey/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome To Survey-Hub</h1>
    <p>This is an example Django survey app</p>
    <a class="btn btn-dark" href="{% url 'poll:index' %}">
        View Available Polls</a
      >
  </div>
  </div>
{% endblock %}

survey/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Survey Hub</a>
	</div>
</nav>

survey/templates/poll/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3 mt-3" href="{% url 'poll:index' %}">Back To Polls</a>

<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'poll:vote' question.id %}"
     method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

survey/templates/poll/index.html
{% extends 'base.html' %}

{% block content %} 
    <h1 class="text-center mb-3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">{{ question.question_text }}</p>
                    <a href="{% url 'poll:detail' question.id %}"
                        class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'poll:results' question.id %}" 
                        class="btn btn-primary btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>No Polls available</h3>
    {% endif %}
{% endblock %}

survey/templates/poll/results.html
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  
        <span class="badge" style="background-color: rgb(1, 157, 4); float:right;">
            {{ choice.votes }} vote{{ choice.votes | pluralize }}
        </span>
	</li>
	{% endfor %}
</ul>

<div id="myChart"></div>

<a class="btn btn-secondary" href="{% url 'poll:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'poll:detail' question.id %}">Vote again?</a>

<script>
	var state = {
		'items': [],
		'values': [],
	}

	var objId = "{{question.id}}"

	var dataURL = `/polls/resultsdata/${objId}`
	$.ajax({
		method: 'GET',
		url: dataURL,
		success: function(response){
			console.log("Response", response)
			for(var i in response){
				var key = Object.keys(response[i])[0]
				var value = Object.values(response[i])[0]

				state.items.push(key)
				state.values.push(value)
			}
			console.log(state)
			buildChart()
		}
	})
	function buildChart(){
		var charData = {
			"type": "bar",
			"scale-x":{
				"values":state.items
			},
			"series":[{
				"values":state.values
			}]
		}

		zingchart.render({
			id: "myChart",
			data: charData
		});
	}

</script>
{% endblock %}